# Generated by Django 4.0.1 on 2022-02-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productivity', '0009_alter_data_importance_alter_networkevents_importance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connections',
            name='contact',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='connections',
            name='desc',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='connections',
            name='field',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='connections',
            name='full_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='connections',
            name='title',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='networkevents',
            name='website_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='networkevents',
            name='website_url',
            field=models.CharField(max_length=140),
        ),
    ]
